// <auto-generated />
using System;
using CodeSharp.Samples.WebAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeSharp.Samples.WebAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeSharp.Core.Models.CompilationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeReport")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<TimeSpan>("CompilationDuration")
                        .HasColumnType("time");

                    b.Property<bool>("CompiledSuccessfully")
                        .HasColumnType("bit");

                    b.Property<bool?>("ExecutedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("ExecutionDuration")
                        .HasColumnType("time");

                    b.Property<string>("Output")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CompilationLogs");
                });

            modelBuilder.Entity("CodeSharp.Core.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("CodeSharp.Core.Models.TestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodeReport")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<TimeSpan>("CompilationDuration")
                        .HasColumnType("time");

                    b.Property<bool>("CompiledSuccessfully")
                        .HasColumnType("bit");

                    b.Property<string>("TestResults")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<bool>("TestedSuccessfully")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("TestingDuration")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("TestLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
